# Site settings
title: Taos Blog
SEOTitle: 涛小苏的博客 | Taos Blog
header-img: img/home-bg.jpg
email: zjusutao@gmail.com
description: "关于程序与设计、天气与数据 | 涛小苏，Web & Mobile Lover，Engineer，| 这里是 @zjusutao 的个人博客，与你一起发现更大的世界。"
keyword: "涛小苏，Taos Blog，zjusutao, 涛小苏的博客, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://zjusutao.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     zjusutao
douban_username:    zjusutao
music163_username:  home?id=5883942
#zhihu_username:     darkblue
github_username:    zjusutao
#twitter_username:   zjusuto
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings

# Netease settings



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Yet another PhD<br>WE ARE 伐木累"
sidebar-avatar: /img/ts_wx.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`




# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "MWR",
        href: "https://www.ametsoc.org/ams/index.cfm/publications/journals/monthly-weather-review/"
    },{
        title: "Google Scholar",
        href: "https://scholar.google.com/"
    },{
        title: "Atmos Forum",
        href: "http://bbs.06climate.com/forum.php"
    },{
        title: "Atmos Sci",
        href: "http://www.dqkxqk.ac.cn/dqkx/dqkx/ch/index.aspx"
    },{
        title: "Acta Meteo",
        href: "http://www.cmsjournal.net/qxxb_cn/ch/index.aspx"
    },{
        title: "Plateau Meteo",
        href: "http://www.gyqx.ac.cn/CN/1000-0534/home.shtml"
    },{
        title: "NCL",
        href: "http://www.ncl.ucar.edu/"
    }
]
